version: "3"
services:
  develop:
    build: .
    ports:
      - "35789:35729"
    environment:
      GATEWAY_URL: http://mymachine:9000
      LOCAL_URL: http://mymachine:3095
      MICROSERVICE_TOKEN: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Im1pY3Jvc2VydmljZSIsImNyZWF0ZWRBdCI6IjIwMTYtMDktMTQifQ.IRCIRm1nfIQTfda_Wb6Pg-341zhV8soAgzw7dd5HxxQ
      GCLOUD_CREDENTIALS: ${GCLOUD_CREDENTIALS}
      AWS_REGION: "us-east-1"
      AWS_ACCESS_KEY_ID: "test"
      AWS_SECRET_ACCESS_KEY: "test"
    command: develop
    volumes:
      - ./app:/opt/adapter-bigquery/app
