version: "3"
services:
  develop:
    build: .
    ports:
      - "35789:35729"
    environment:
      CT_URL: http://mymachine:9000
      LOCAL_URL: http://mymachine:3095
      CT_TOKEN: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Im1pY3Jvc2VydmljZSIsImNyZWF0ZWRBdCI6IjIwMTYtMDktMTQifQ.IRCIRm1nfIQTfda_Wb6Pg-341zhV8soAgzw7dd5HxxQ
      API_VERSION: v1
      GCLOUD_CREDENTIALS: ${GCLOUD_CREDENTIALS}
    command: develop
    volumes:
      - ./app:/opt/adapter-bigquery/app
