apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    name: bigquery
  name: bigquery
spec:
  revisionHistoryLimit: 0
  template:
    metadata:
      labels:
        name: bigquery
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: type
                    operator: In
                    values:
                      - apps
      containers:
        - name: bigquery
          image: vizzuality/bigquery
          imagePullPolicy: Always
          resources:
            requests:
              cpu: "0.5"
              memory: "256M"
            limits:
              cpu: "1"
              memory: "512M"
          args:
            - start
          env:
            - name: PORT
              value: "3095"
            - name: NODE_ENV
              value: staging
            - name: NODE_PATH
              value: app/src
            - name: LOCAL_URL
              value: http://bigquery.default.svc.cluster.local:3095
            - name: GCLOUD_CREDENTIALS
              valueFrom:
                secretKeyRef:
                  name: mssecrets
                  key: BIGQUERY_GCLOUD_CREDENTIALS
            - name: CT_URL
              valueFrom:
                secretKeyRef:
                  name: mssecrets
                  key: CT_URL
            - name: CT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: mssecrets
                  key: CT_TOKEN
            - name: CT_REGISTER_MODE
              valueFrom:
                secretKeyRef:
                  name: mssecrets
                  key: CT_REGISTER_MODE
            - name: API_VERSION
              valueFrom:
                secretKeyRef:
                  name: mssecrets
                  key: API_VERSION
          ports:
            - containerPort: 3095
          readinessProbe:
            httpGet:
              scheme: HTTP
              path: /healthcheck
              port: 3095
            initialDelaySeconds: 30
            timeoutSeconds: 5
            periodSeconds: 15
          livenessProbe:
            httpGet:
              scheme: HTTP
              path: /healthcheck
              port: 3095
            failureThreshold: 3
            initialDelaySeconds: 30
            timeoutSeconds: 5
            periodSeconds: 15

      restartPolicy: Always
